version: '3'

services:
  api:
    container_name: nest_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${API_PORT}:${API_PORT}'
    volumes:
      - .:/home/nest-api
    environment:
      DB_HOST: 'database'
      DB_PORT: 5432

  database:
    container_name: 'nest_api_db'
    image: postgres
    ports:
      - '5433:5432'
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
